# Generated by Django 4.0.1 on 2022-01-10 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_new1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new1',
            old_name='name',
            new_name='username',
        ),
    ]
