# Generated by Django 4.0.1 on 2022-01-11 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_name_new1_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new1',
            old_name='password',
            new_name='password1',
        ),
    ]
