# Generated by Django 4.0.1 on 2022-01-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_password_new1_password1'),
    ]

    operations = [
        migrations.CreateModel(
            name='new2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
                ('cemail', models.CharField(max_length=30)),
                ('cnumber', models.CharField(max_length=30)),
                ('csub', models.CharField(max_length=30)),
                ('cmessage', models.CharField(max_length=30)),
            ],
        ),
    ]
